[project]
name = "online-store"
version = "0.1.0"
description = "Online store implementation"
authors = [
    {name = "Victor",email = "Nechaevvictor199220@gmail.com"}
]
license = {text = "mit"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest (>=9.0.0,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
black = "^25.9.0"
mypy = "^1.18.2"


[tool.poetry.group.lint.dependencies]
isort = "^7.0.0"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.flake8]
max-line-length = 88
extend-ignore = "E203, W503, E501, F401, F403"
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    ".env",
    "env",
    "venv",
    "build",
    "dist",
    ".pytest_cache",
    ".mypy_cache",
    ".coverage",
    "htmlcov",
    "*.egg-info",
    "data",
    "logs",
    "temp",
    "tmp"
]
filename = "*.py"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = [
    "--cov=src",
    "--cov-report=html",
    "--cov-report=term-missing"
]
filterwarnings = [
    "ignore::DeprecationWarning"
]
